function [channelIndices, targetSubjectIDs] = ...
    build_correlation_development_indices( ...
        developmentData, candidateModels, cvPartition, config)
%BUILD_CORRELATION_DEVELOPMENT_INDICES Fixed-parameter OOF indices.

    nChannels = height(candidateModels);

    firstChannel = get_channel_data( ...
        developmentData, char(candidateModels.Channel(1)));

    targetSubjectIDs = firstChannel.group1IDs;
    referenceSubjectIDs = firstChannel.group0IDs;

    nTarget = numel(targetSubjectIDs);
    channelIndices = nan(nTarget, nChannels);

    for k = 1:nChannels
        channelName = char(candidateModels.Channel(k));

        fprintf('Building correlation development indices %d/%d: %s\n', ...
            k, nChannels, channelName);

        channelData = get_channel_data( ...
            developmentData, channelName);

        if ~isequal(channelData.group1IDs(:), targetSubjectIDs(:))
            error('Target subject ordering differs for channel %s.', ...
                channelName);
        end

        if ~isequal(channelData.group0IDs(:), referenceSubjectIDs(:))
            error('Reference subject ordering differs for channel %s.', ...
                channelName);
        end

        allSignals = [ ...
            channelData.group1Signals; ...
            channelData.group0Signals];

        filtered = preprocess_channel_signals( ...
            allSignals, ...
            config.samplingRate, ...
            candidateModels.LowCutoffHz(k), ...
            candidateModels.HighCutoffHz(k), ...
            config.notchFrequencyHz, ...
            config.notchQualityFactor);

        features = extract_lpc_features( ...
            filtered, candidateModels.LPCOrder(k));

        targetFeatures = features(1:nTarget,:);
        referenceFeatures = features(nTarget+1:end,:);

        result = evaluate_correlation_leapd( ...
            targetFeatures, ...
            referenceFeatures, ...
            [], ...
            cvPartition, ...
            candidateModels.PCADimension(k), ...
            config.useNormalizedProjection);

        channelIndices(:,k) = result.LEAPDIndices;
    end
end
