function channelIndices = build_binary_development_indices( ...
    developmentData, candidateModels, cvPartition, config)
%BUILD_BINARY_DEVELOPMENT_INDICES Fixed-parameter out-of-fold LEAPD indices.

    nChannels = height(candidateModels);

    [~, referenceClasses, referenceSubjectIDs] = ...
        get_binary_channel_data( ...
            developmentData, char(candidateModels.Channel(1)));

    nSubjects = numel(referenceSubjectIDs);
    channelIndices = nan(nSubjects, nChannels);

    for k = 1:nChannels
        channelName = char(candidateModels.Channel(k));

        fprintf('Building binary development indices %d/%d: %s\n', ...
            k, nChannels, channelName);

        [signals, classes, subjectIDs] = ...
            get_binary_channel_data( ...
                developmentData, channelName);

        if ~isequal(classes(:), referenceClasses(:)) || ...
                ~isequal(subjectIDs(:), referenceSubjectIDs(:))
            error('Subject/class ordering differs for channel %s.', ...
                channelName);
        end

        filtered = preprocess_channel_signals( ...
            signals, ...
            config.samplingRate, ...
            candidateModels.LowCutoffHz(k), ...
            candidateModels.HighCutoffHz(k), ...
            config.notchFrequencyHz, ...
            config.notchQualityFactor);

        features = extract_lpc_features( ...
            filtered, candidateModels.LPCOrder(k));

        result = cross_validate_binary_leapd( ...
            features, ...
            classes, ...
            subjectIDs, ...
            cvPartition, ...
            candidateModels.PCADimension(k), ...
            config.useNormalizedProjection);

        channelIndices(:,k) = result.LEAPDIndices;
    end
end
