function result = cross_validate_binary_leapd( ...
    features, classes, subjectIDs, cvPartition, ...
    pcaDimension, useNormalizedProjection)
%CROSS_VALIDATE_BINARY_LEAPD Evaluate one fixed single-channel model.

    nSubjects = size(features,1);

    scores = nan(nSubjects,1);
    predictions = nan(nSubjects,1);

    for fold = 1:cvPartition.NumTestSets
        trainIndex = training(cvPartition, fold);
        testIndex = test(cvPartition, fold);

        model = fit_leapd_model( ...
            features(trainIndex,:), ...
            classes(trainIndex), ...
            pcaDimension);

        [foldScores, foldPredictions] = ...
            predict_leapd_model( ...
                model, ...
                features(testIndex,:), ...
                useNormalizedProjection);

        scores(testIndex) = foldScores;
        predictions(testIndex) = foldPredictions;
    end

    if any(isnan(scores)) || any(isnan(predictions))
        error('Some subjects did not receive a cross-validated prediction.');
    end

    metrics = evaluate_predictions(classes, predictions);

    result = struct();
    result.Accuracy = 100 * metrics.Accuracy;
    result.BalancedAccuracy = 100 * metrics.BalancedAccuracy;
    result.Sensitivity = 100 * metrics.Sensitivity;
    result.Specificity = 100 * metrics.Specificity;
    result.LEAPDIndices = scores;
    result.Predictions = predictions;

    result.SubjectTable = table( ...
        string(subjectIDs(:)), ...
        classes(:), ...
        predictions, ...
        scores, ...
        'VariableNames', { ...
            'SubjectID', ...
            'TrueClass', ...
            'PredictedClass', ...
            'LEAPDScore'});
end
