function finalModels = fit_binary_channel_models( ...
    developmentData, candidateModels, config)
%FIT_BINARY_CHANNEL_MODELS Fit final class models on all development data.

    nChannels = height(candidateModels);
    finalModels = repmat(struct(), nChannels, 1);

    for k = 1:nChannels
        channelName = char(candidateModels.Channel(k));

        fprintf('Fitting binary channel %d/%d: %s\n', ...
            k, nChannels, channelName);

        [signals, classes] = ...
            get_binary_channel_data( ...
                developmentData, channelName);

        filtered = preprocess_channel_signals( ...
            signals, ...
            config.samplingRate, ...
            candidateModels.LowCutoffHz(k), ...
            candidateModels.HighCutoffHz(k), ...
            config.notchFrequencyHz, ...
            config.notchQualityFactor);

        features = extract_lpc_features( ...
            filtered, candidateModels.LPCOrder(k));

        model = fit_leapd_model( ...
            features, ...
            classes, ...
            candidateModels.PCADimension(k));

        model.Channel = string(channelName);
        model.LowCutoffHz = candidateModels.LowCutoffHz(k);
        model.HighCutoffHz = candidateModels.HighCutoffHz(k);
        model.LPCOrder = candidateModels.LPCOrder(k);

        finalModels(k) = model;
    end
end
