function filteredSignals = preprocess_channel_signals( ...
    signals, samplingRate, lowCutoffHz, highCutoffHz, ...
    notchFrequencyHz, notchQualityFactor)
%PREPROCESS_CHANNEL_SIGNALS Average segments, notch, band-pass, and normalize.
%
% Processing order for each subject:
%   1. Normalize each segment independently to unit energy.
%   2. Average segments.
%   3. Apply the line-noise notch filter.
%   4. Apply the sixth-order Butterworth candidate band-pass filter.
%   5. Normalize the final signal to unit energy.
%
% This wrapper preserves the public preprocessing interface used outside
% the exhaustive search. The exhaustive search uses the same operations via
% prepare_channel_signals and filter_prepared_channel_signals, but avoids
% repeating the notch step for every candidate frequency band.

    preparedSignals = prepare_channel_signals( ...
        signals, ...
        samplingRate, ...
        notchFrequencyHz, ...
        notchQualityFactor);

    filterBank = build_filter_bank( ...
        [lowCutoffHz highCutoffHz], ...
        samplingRate);

    filteredSignals = filter_prepared_channel_signals( ...
        preparedSignals, ...
        filterBank, ...
        1);
end
