function [channelIndices, classes, subjectIDs] = ...
    score_binary_channel_models(testData, finalModels, config)
%SCORE_BINARY_CHANNEL_MODELS Apply fixed development models to test data.

    nChannels = numel(finalModels);

    [~, classes, subjectIDs] = ...
        get_binary_channel_data( ...
            testData, char(finalModels(1).Channel));

    nSubjects = numel(subjectIDs);
    channelIndices = nan(nSubjects, nChannels);

    if config.useParallel
        parfor k = 1:nChannels
            [scores, currentClasses, currentSubjectIDs] = ...
                score_one_binary_channel( ...
                    testData, finalModels(k), config);

            if ~isequal(currentClasses(:), classes(:)) || ...
                    ~isequal(currentSubjectIDs(:), subjectIDs(:))
                error('Test subject/class ordering differs for channel %s.', ...
                    finalModels(k).Channel);
            end

            channelIndices(:,k) = scores;
        end
    else
        for k = 1:nChannels
            fprintf('Scoring binary channel %d/%d: %s\n', ...
                k, nChannels, finalModels(k).Channel);

            [scores, currentClasses, currentSubjectIDs] = ...
                score_one_binary_channel( ...
                    testData, finalModels(k), config);

            if ~isequal(currentClasses(:), classes(:)) || ...
                    ~isequal(currentSubjectIDs(:), subjectIDs(:))
                error('Test subject/class ordering differs for channel %s.', ...
                    finalModels(k).Channel);
            end

            channelIndices(:,k) = scores;
        end
    end
end


function [scores, classes, subjectIDs] = ...
    score_one_binary_channel(testData, model, config)

    [signals, classes, subjectIDs] = ...
        get_binary_channel_data( ...
            testData, char(model.Channel));

    filtered = preprocess_channel_signals( ...
        signals, ...
        config.samplingRate, ...
        model.LowCutoffHz, ...
        model.HighCutoffHz, ...
        config.notchFrequencyHz, ...
        config.notchQualityFactor);

    features = extract_lpc_features( ...
        filtered, model.LPCOrder);

    scores = predict_leapd_model( ...
        model, ...
        features, ...
        config.useNormalizedProjection);
end
