function [channelIndices, subjectIDs] = ...
    score_correlation_channel_models( ...
        testData, finalModels, config)
%SCORE_CORRELATION_CHANNEL_MODELS Apply fixed development models to test data.

    nChannels = numel(finalModels);

    [~, subjectIDs] = get_target_channel_data( ...
        testData, char(finalModels(1).Channel));

    nSubjects = numel(subjectIDs);
    channelIndices = nan(nSubjects, nChannels);

    if config.useParallel
        parfor k = 1:nChannels
            [scores, currentSubjectIDs] = ...
                score_one_correlation_channel( ...
                    testData, finalModels(k), config);

            if ~isequal(currentSubjectIDs(:), subjectIDs(:))
                error('Test subject ordering differs for channel %s.', ...
                    finalModels(k).Channel);
            end

            channelIndices(:,k) = scores;
        end
    else
        for k = 1:nChannels
            fprintf('Scoring correlation channel %d/%d: %s\n', ...
                k, nChannels, finalModels(k).Channel);

            [scores, currentSubjectIDs] = ...
                score_one_correlation_channel( ...
                    testData, finalModels(k), config);

            if ~isequal(currentSubjectIDs(:), subjectIDs(:))
                error('Test subject ordering differs for channel %s.', ...
                    finalModels(k).Channel);
            end

            channelIndices(:,k) = scores;
        end
    end
end


function [scores, subjectIDs] = ...
    score_one_correlation_channel(testData, model, config)

    [signals, subjectIDs] = ...
        get_target_channel_data( ...
            testData, char(model.Channel));

    filtered = preprocess_channel_signals( ...
        signals, ...
        config.samplingRate, ...
        model.LowCutoffHz, ...
        model.HighCutoffHz, ...
        config.notchFrequencyHz, ...
        config.notchQualityFactor);

    features = extract_lpc_features( ...
        filtered, model.LPCOrder);

    distanceToTarget = batch_distance_to_hyperplane( ...
        features, ...
        model.TargetBasis, ...
        model.TargetMean, ...
        config.useNormalizedProjection);

    distanceToReference = batch_distance_to_hyperplane( ...
        features, ...
        model.ReferenceBasis, ...
        model.ReferenceMean, ...
        config.useNormalizedProjection);

    denominator = distanceToTarget + distanceToReference;

    scores = nan(size(denominator));
    valid = denominator > eps;

    scores(valid) = ...
        distanceToReference(valid) ./ denominator(valid);
end
