function bestRow = ...
    search_one_channel(dataset, channelName, context, config)
%SEARCH_ONE_CHANNEL Fast exhaustive hyperparameter search for one channel.
%
% Only the winning parameter set is retained. Subject-level LEAPD scores
% are computed once after the winning hyperparameters are known.

    switch lower(config.analysisType)
        case 'binary'
            bestRow = search_binary_channel( ...
                dataset, channelName, context, config);

        case 'correlation'
            bestRow = search_correlation_channel( ...
                dataset, channelName, context, config);

        otherwise
            error('Unknown analysisType: "%s".', config.analysisType);
    end
end


function bestRow = search_binary_channel( ...
    dataset, channelName, context, config)

    [signals, classes, subjectIDs] = ...
        get_binary_channel_data(dataset, channelName);

    if ~isequal(subjectIDs(:), context.subjectIDs(:)) || ...
            ~isequal(classes(:), context.classes(:))
        error('Subject identity or class ordering differs for channel %s.', ...
            channelName);
    end

    preparedSignals = prepare_channel_signals(signals);

    bestAccuracy = -inf;
    bestLow = NaN;
    bestHigh = NaN;
    bestOrder = NaN;
    bestDimension = NaN;
    bestFeatures = [];

    validBands = context.validBands;

    for bandIndex = 1:size(validBands,1)
        low = validBands(bandIndex,1);
        high = validBands(bandIndex,2);

        filtered = filter_prepared_channel_signals( ...
            preparedSignals, ...
            context.filterBank, ...
            bandIndex);

        featuresByOrder = extract_lpc_features_all_orders( ...
            filtered, config.lpcOrders);

        for orderIndex = 1:numel(config.lpcOrders)
            order = config.lpcOrders(orderIndex);
            features = featuresByOrder{orderIndex};

            maximumDimension = min( ...
                order - 1, context.maximumSampleDimension);

            if maximumDimension < 1
                continue;
            end

            accuracies = cross_validate_binary_leapd_fast( ...
                features, ...
                classes, ...
                context.foldCache, ...
                maximumDimension, ...
                config.useNormalizedProjection);

            [currentAccuracy, currentDimension] = max(accuracies);

            % Accuracy is the ONLY binary model-selection criterion.
            % Ties retain the first encountered parameter combination.
            if currentAccuracy > bestAccuracy
                bestAccuracy = currentAccuracy;
                bestLow = low;
                bestHigh = high;
                bestOrder = order;
                bestDimension = currentDimension;
                bestFeatures = features;
            end
        end
    end

    if isempty(bestFeatures) || ~isfinite(bestAccuracy)
        error(['No valid parameter combination was evaluated ', ...
               'for channel %s.'], channelName);
    end

    % Re-run ONLY the winning model with the standard CV function to obtain
    % subject-level out-of-fold LEAPD scores and predictions.
    finalCV = cross_validate_binary_leapd( ...
        bestFeatures, ...
        classes, ...
        subjectIDs, ...
        context.cvPartition, ...
        bestDimension, ...
        config.useNormalizedProjection);

    if abs(finalCV.Accuracy - bestAccuracy) > 1e-10
        error([ ...
            'Fast and standard binary CV disagree for channel %s. ' ...
            'Fast = %.12g, standard = %.12g.'], ...
            channelName, bestAccuracy, finalCV.Accuracy);
    end

    bestRow = table( ...
        string(channelName), ...
        bestLow, ...
        bestHigh, ...
        bestOrder, ...
        bestDimension, ...
        bestAccuracy, ...
        {string(subjectIDs(:))}, ...
        {classes(:)}, ...
        {finalCV.LEAPDIndices(:)}, ...
        {finalCV.Predictions(:)}, ...
        'VariableNames', { ...
            'Channel', ...
            'LowCutoffHz', ...
            'HighCutoffHz', ...
            'LPCOrder', ...
            'PCADimension', ...
            'CVAccuracy', ...
            'SubjectIDs', ...
            'TrueClasses', ...
            'LEAPDScores', ...
            'PredictedClasses'});
end


function bestRow = search_correlation_channel( ...
    dataset, channelName, context, config)

    channelData = get_channel_data(dataset, channelName);

    if ~isequal(channelData.group1IDs(:), ...
            context.targetSubjectIDs(:))
        error('Target subject ordering differs for channel %s.', ...
            channelName);
    end

    if ~isequal(channelData.group0IDs(:), ...
            context.referenceSubjectIDs(:))
        error('Reference subject ordering differs for channel %s.', ...
            channelName);
    end

    nTarget = numel(channelData.group1Signals);

    allSignals = [ ...
        channelData.group1Signals; ...
        channelData.group0Signals];

    preparedSignals = prepare_channel_signals(allSignals);

    bestRho = NaN;
    bestLow = NaN;
    bestHigh = NaN;
    bestOrder = NaN;
    bestDimension = NaN;
    bestFeatures = [];

    validBands = context.validBands;

    for bandIndex = 1:size(validBands,1)
        low = validBands(bandIndex,1);
        high = validBands(bandIndex,2);

        filtered = filter_prepared_channel_signals( ...
            preparedSignals, ...
            context.filterBank, ...
            bandIndex);

        featuresByOrder = extract_lpc_features_all_orders( ...
            filtered, config.lpcOrders);

        for orderIndex = 1:numel(config.lpcOrders)
            order = config.lpcOrders(orderIndex);
            features = featuresByOrder{orderIndex};

            targetFeatures = features(1:nTarget,:);
            referenceFeatures = features(nTarget+1:end,:);

            maximumDimension = min( ...
                order - 1, context.maximumSampleDimension);

            if maximumDimension < 1
                continue;
            end

            rhos = evaluate_correlation_leapd_fast( ...
                targetFeatures, ...
                referenceFeatures, ...
                context.targetValues, ...
                context.foldCache, ...
                maximumDimension, ...
                config.useNormalizedProjection);

            [currentRho, currentDimension] = ...
                select_best_rho(rhos, config.selectionCriterion);

            if is_better_rho( ...
                    currentRho, bestRho, config.selectionCriterion)
                bestRho = currentRho;
                bestLow = low;
                bestHigh = high;
                bestOrder = order;
                bestDimension = currentDimension;
                bestFeatures = features;
            end
        end
    end

    if isempty(bestFeatures) || ~isfinite(bestRho)
        error('No finite correlation was obtained for channel %s.', ...
            channelName);
    end

    targetFeatures = bestFeatures(1:nTarget,:);
    referenceFeatures = bestFeatures(nTarget+1:end,:);

    % Re-run ONLY the winning model to store exact subject-level OOF scores
    % and the associated Spearman p-value. If numberOfFolds = 1 these are
    % specifically LOOCV scores.
    finalResult = evaluate_correlation_leapd( ...
        targetFeatures, ...
        referenceFeatures, ...
        context.targetValues, ...
        context.cvPartition, ...
        bestDimension, ...
        config.useNormalizedProjection);

    if abs(finalResult.Rho - bestRho) > 1e-10
        error([ ...
            'Fast and standard correlation evaluation disagree for ', ...
            'channel %s. Fast rho = %.12g, standard rho = %.12g.'], ...
            channelName, bestRho, finalResult.Rho);
    end

    bestRow = table( ...
        string(channelName), ...
        bestLow, ...
        bestHigh, ...
        bestOrder, ...
        bestDimension, ...
        finalResult.Rho, ...
        finalResult.PValue, ...
        {string(context.targetSubjectIDs(:))}, ...
        {context.targetValues(:)}, ...
        {finalResult.LEAPDIndices(:)}, ...
        'VariableNames', { ...
            'Channel', ...
            'LowCutoffHz', ...
            'HighCutoffHz', ...
            'LPCOrder', ...
            'PCADimension', ...
            'SpearmanRho', ...
            'PValue', ...
            'SubjectIDs', ...
            'TargetValues', ...
            'LEAPDScores'});
end


function [bestRho, bestDimension] = ...
    select_best_rho(rhos, criterion)

    bestRho = NaN;
    bestDimension = NaN;

    for dimension = 1:numel(rhos)
        candidate = rhos(dimension);

        if is_better_rho(candidate, bestRho, criterion)
            bestRho = candidate;
            bestDimension = dimension;
        end
    end
end


function tf = is_better_rho(candidate, currentBest, criterion)
    if ~isfinite(candidate)
        tf = false;
        return;
    end

    if ~isfinite(currentBest)
        tf = true;
        return;
    end

    switch lower(criterion)
        case 'min'
            tf = candidate < currentBest;

        case 'max'
            tf = candidate > currentBest;

        case 'maxabs'
            tf = abs(candidate) > abs(currentBest);

        otherwise
            error('Unknown selection criterion: "%s".', criterion);
    end
end
