clear; clc; close all;

%% ============================================================
% ENHANCED BINARY LEAPD OOS CHANNEL SEARCH
%
% Binary mapping:
%   Class 1 = TBI
%   Class 0 = Control
%
% LEAPD score:
%   score > 0.5  -> TBI
%   score <= 0.5 -> Control
%
% Search strategy:
%
%   1-4 channels:
%       exact exhaustive
%
%   5 channels:
%       exact exhaustive, memory-safe
%
%   6-10 channels:
%       wide beam search
%       beamWidth = 1000
%       tie-aware retention
%
%   10-channel refinement:
%       top 100 beam solutions
%           ->
%       iterative 1-channel swap
%           ->
%       deduplicate local optima
%           ->
%       exhaustive 2-channel swap around top 20
%           ->
%       final iterative 1-channel swap
%
% IMPORTANT:
%   This changes ONLY the search strategy.
%   LEAPD feature extraction/model/scoring are unchanged.
%
% Search objective:
%   Mean balanced OOS accuracy over the 10,000 repeats.
%
% For speed, the search uses the mathematically equivalent
% weighted-subject representation of the 10,000 repeats.
%
% Final reported metrics are calculated explicitly across
% all 10,000 balanced repeats.
% ============================================================


%% ============================================================
% SELECT DATASET
% ============================================================

% analysisMode = "acute";
analysisMode = "chronic";


%% ============================================================
% PATHS
% ============================================================

projectRoot = fileparts(mfilename('fullpath'));

functionsFolder = ...
    fullfile(projectRoot, 'functions');

resultsFolder = ...
    fullfile(projectRoot, 'results');

developmentFile = ...
    fullfile( ...
        projectRoot, ...
        'data', ...
        'TBI_EO_100s_LEAPD_TRAIN.mat');

hyperparameterFile = ...
    fullfile( ...
        resultsFolder, ...
        'hyperparameter_results_binary_low2p5to95_high5to100_step1.mat');


switch lower(analysisMode)

    case "acute"

        testFile = ...
            fullfile( ...
                projectRoot, ...
                'data', ...
                'TBI_EO_100s_LEAPD_TEST.mat');

        subsetFile = ...
            fullfile( ...
                resultsFolder, ...
                'enhanced_acute_balanced_subsets_10000.mat');

        scoreFile = ...
            fullfile( ...
                resultsFolder, ...
                'enhanced_acute_single_channel_scores.mat');

        outputMAT = ...
            fullfile( ...
                resultsFolder, ...
                'acute_enhanced_beam_search_1_to_10.mat');

        outputExcel = ...
            fullfile( ...
                resultsFolder, ...
                'acute_enhanced_beam_search_1_to_10.xlsx');


    case "chronic"

        testFile = ...
            fullfile( ...
                projectRoot, ...
                'data', ...
                'TBI_EO_100s_CHRONIC_OOS.mat');

        subsetFile = ...
            fullfile( ...
                resultsFolder, ...
                'enhanced_chronic_balanced_subsets_10000.mat');

        scoreFile = ...
            fullfile( ...
                resultsFolder, ...
                'enhanced_chronic_single_channel_scores.mat');

        outputMAT = ...
            fullfile( ...
                resultsFolder, ...
                'chronic_enhanced_beam_search_1_to_10.mat');

        outputExcel = ...
            fullfile( ...
                resultsFolder, ...
                'chronic_enhanced_beam_search_1_to_10.xlsx');


    otherwise

        error('analysisMode must be "acute" or "chronic".');

end


addpath(functionsFolder);

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end


%% ============================================================
% SETTINGS
% ============================================================

% These settings are specific to the OOS combination search.
% Preprocessing/model settings used during development
% (sampling rate, notch settings, projection option) are loaded
% directly from the saved hyperparameter-search config below.

useParallel = true;

numberOfRepeats = 10000;

subjectsPerClass = 13;

randomSeed = 1;


% ------------------------
% ENHANCED SEARCH SETTINGS
% ------------------------

beamWidth = 1000;

% Keep ties at beam cutoff, but avoid pathological explosion.
maximumBeamRetained = 5000;

tieTolerance = 1e-12;


% One-swap refinement:
localSwapTopN = 100;


% Two-swap refinement:
twoSwapTopN = 20;


% Batch size for vectorized candidate scoring.
% Lower if RAM becomes limiting.
batchSize = 5000;


%% ============================================================
% VERIFY FILES
% ============================================================

if ~isfile(developmentFile)
    error('Development file not found:\n%s', developmentFile);
end

if ~isfile(testFile)
    error('Test file not found:\n%s', testFile);
end

if ~isfile(hyperparameterFile)
    error('Hyperparameter file not found:\n%s', hyperparameterFile);
end


%% ============================================================
% PARALLEL POOL
% ============================================================

if useParallel

    pool = gcp('nocreate');

    if isempty(pool)
        pool = parpool;
    end

    % Make all external LEAPD helper functions explicitly available
    % to the workers before any parfor block begins.
    functionInfo = dir(fullfile(functionsFolder, '*.m'));

    functionFiles = fullfile( ...
        {functionInfo.folder}, ...
        {functionInfo.name});

    addAttachedFiles(pool, functionFiles);

    fprintf('\nParallel workers: %d\n', pool.NumWorkers);

end


%% ============================================================
% LOAD DEVELOPMENT HYPERPARAMETERS + PREPROCESSING SETTINGS
% ============================================================

fprintf('\n============================================================\n');
fprintf('LOADING DEVELOPMENT PARAMETERS\n');
fprintf('============================================================\n');

candidateModels = ...
    load_candidate_models( ...
        hyperparameterFile, ...
        {});

hyperparameterData = ...
    load( ...
        hyperparameterFile, ...
        'config');

if ~isfield(hyperparameterData, 'config')

    error( ...
        ['The hyperparameter result file does not contain ' ...
         'the saved development config.']);

end

trainingConfig = ...
    hyperparameterData.config;

% Use the same basic settings as the development hyperparameter search.
if isfield(trainingConfig, 'samplingRate')
    samplingRate = trainingConfig.samplingRate;
else
    samplingRate = 500;
    warning('samplingRate was not saved in config. Using default 500 Hz.');
end

% The GitHub-optimized training pipeline should save these fields.
% If an older result file does not contain them, the code falls back to
% the intended TBI scalp EEG line-noise settings used in this project.
if isfield(trainingConfig, 'notchFrequencyHz')
    notchFrequencyHz = trainingConfig.notchFrequencyHz;
else
    notchFrequencyHz = 60;
    warning(['notchFrequencyHz was not saved in config. ' ...
             'Using default 60 Hz. Make sure the training run used the same setting.']);
end

if isfield(trainingConfig, 'notchQualityFactor')
    notchQualityFactor = trainingConfig.notchQualityFactor;
else
    notchQualityFactor = 35;
    warning(['notchQualityFactor was not saved in config. ' ...
             'Using default Q = 35. Make sure the training run used the same setting.']);
end

if isfield(trainingConfig, 'useNormalizedProjection')
    useNormalizedProjection = trainingConfig.useNormalizedProjection;
else
    useNormalizedProjection = false;
    warning('useNormalizedProjection was not saved in config. Using default false.');
end

nChannels = ...
    height(candidateModels);

channelNames = ...
    string(candidateModels.Channel(:));

fprintf('Channels: %d\n', nChannels);
fprintf('Sampling rate: %.1f Hz\n', samplingRate);
fprintf('Notch frequency: %.1f Hz\n', notchFrequencyHz);
fprintf('Notch quality factor: %.3f\n', notchQualityFactor);
fprintf('Normalized projection: %d\n', useNormalizedProjection);


%% ============================================================
% LOAD DEVELOPMENT + TEST DATA
% ============================================================

developmentData = ...
    load_leapd_dataset(developmentFile);


testData = ...
    load_leapd_dataset(testFile);


[~, developmentClasses, developmentSubjectIDs] = ...
    get_binary_channel_data( ...
        developmentData, ...
        char(candidateModels.Channel(1)));


[~, testClasses, testSubjectIDs] = ...
    get_binary_channel_data( ...
        testData, ...
        char(candidateModels.Channel(1)));


developmentClasses = ...
    developmentClasses(:);


testClasses = ...
    testClasses(:);


testSubjectIDs = ...
    cellstr(string(testSubjectIDs(:)));


nTBI = ...
    sum(testClasses == 1);


nControl = ...
    sum(testClasses == 0);


fprintf('\nAnalysis: %s\n', upper(analysisMode));

fprintf('Development subjects: %d\n', ...
    numel(developmentClasses));

fprintf('OOS subjects: %d\n', ...
    numel(testClasses));

fprintf('TBI class 1: %d\n', nTBI);

fprintf('Control class 0: %d\n', nControl);


if nControl ~= subjectsPerClass

    error( ...
        'Expected %d controls; found %d.', ...
        subjectsPerClass, ...
        nControl);

end


%% ============================================================
% VERIFY ORDER
%
% get_binary_channel_data guarantees:
%
%   class 1 first
%   class 0 second
% ============================================================

if ~all(testClasses(1:nTBI) == 1)

    error('Unexpected test subject ordering.');

end


if ~all(testClasses(nTBI+1:end) == 0)

    error('Unexpected control ordering.');

end


tbiRows = ...
    find(testClasses == 1);


controlRows = ...
    find(testClasses == 0);


%% ============================================================
% BUILD / LOAD SINGLE-CHANNEL SCORES
% ============================================================

fprintf('\n============================================================\n');
fprintf('SINGLE-CHANNEL LEAPD SCORES\n');
fprintf('============================================================\n');


rebuildScoreCache = true;


% Store the exact selected per-channel development parameters that
% determine feature extraction and LEAPD model fitting.
currentModelSignature = ...
    candidateModels(:, { ...
        'Channel', ...
        'LowCutoffHz', ...
        'HighCutoffHz', ...
        'LPCOrder', ...
        'PCADimension'});


%% ------------------------------------------------------------
% Check whether an existing score cache is fully compatible
% ------------------------------------------------------------

if isfile(scoreFile)

    fprintf('Checking existing score cache...\n');

    S = load(scoreFile);

    cacheCompatible = true;


    % Subject order
    if ~isfield(S, 'savedSubjectIDs') || ...
            ~isequal( ...
                string(S.savedSubjectIDs(:)), ...
                string(testSubjectIDs(:)))

        cacheCompatible = false;

    end


    % Channel order
    if ~isfield(S, 'savedChannelNames') || ...
            ~isequal( ...
                string(S.savedChannelNames(:)), ...
                channelNames(:))

        cacheCompatible = false;

    end


    % Exact selected hyperparameters
    if ~isfield(S, 'savedModelSignature') || ...
            ~isequaln( ...
                S.savedModelSignature, ...
                currentModelSignature)

        cacheCompatible = false;

    end


    % Sampling rate
    if ~isfield(S, 'savedSamplingRate') || ...
            ~isequaln( ...
                S.savedSamplingRate, ...
                samplingRate)

        cacheCompatible = false;

    end


    % Notch frequency
    if ~isfield(S, 'savedNotchFrequencyHz') || ...
            ~isequaln( ...
                S.savedNotchFrequencyHz, ...
                notchFrequencyHz)

        cacheCompatible = false;

    end


    % Notch quality factor
    if ~isfield(S, 'savedNotchQualityFactor') || ...
            ~isequaln( ...
                S.savedNotchQualityFactor, ...
                notchQualityFactor)

        cacheCompatible = false;

    end


    % LEAPD distance/projection definition
    if ~isfield(S, 'savedUseNormalizedProjection') || ...
            ~isequaln( ...
                S.savedUseNormalizedProjection, ...
                useNormalizedProjection)

        cacheCompatible = false;

    end


    if cacheCompatible

        fprintf('Compatible score cache found. Loading...\n');

        singleChannelScores = ...
            S.singleChannelScores;

        rebuildScoreCache = false;

    else

        fprintf([ ...
            'Existing score cache does not match the current ' ...
            'development settings and will be rebuilt.\n']);

    end

end


%% ------------------------------------------------------------
% Build single-channel OOS scores when needed
% ------------------------------------------------------------

if rebuildScoreCache

    fprintf('Building development features...\n');

    developmentFeatures = ...
        build_selected_channel_features( ...
            developmentData, ...
            candidateModels, ...
            samplingRate, ...
            notchFrequencyHz, ...
            notchQualityFactor);


    fprintf('Building OOS features...\n');

    testFeatures = ...
        build_selected_channel_features( ...
            testData, ...
            candidateModels, ...
            samplingRate, ...
            notchFrequencyHz, ...
            notchQualityFactor);


    singleChannelScores = ...
        nan( ...
            nChannels, ...
            numel(testClasses));


    if useParallel

        parfor ch = 1:nChannels

            model = ...
                fit_leapd_model( ...
                    developmentFeatures{ch}, ...
                    developmentClasses, ...
                    candidateModels.PCADimension(ch));


            scores = ...
                predict_leapd_model( ...
                    model, ...
                    testFeatures{ch}, ...
                    useNormalizedProjection);


            singleChannelScores(ch,:) = ...
                scores(:)';

        end

    else

        for ch = 1:nChannels

            model = ...
                fit_leapd_model( ...
                    developmentFeatures{ch}, ...
                    developmentClasses, ...
                    candidateModels.PCADimension(ch));


            scores = ...
                predict_leapd_model( ...
                    model, ...
                    testFeatures{ch}, ...
                    useNormalizedProjection);


            singleChannelScores(ch,:) = ...
                scores(:)';

        end

    end


    savedSubjectIDs = ...
        testSubjectIDs;


    savedChannelNames = ...
        channelNames;


    savedModelSignature = ...
        currentModelSignature;


    savedSamplingRate = ...
        samplingRate;


    savedNotchFrequencyHz = ...
        notchFrequencyHz;


    savedNotchQualityFactor = ...
        notchQualityFactor;


    savedUseNormalizedProjection = ...
        useNormalizedProjection;


    save( ...
        scoreFile, ...
        'singleChannelScores', ...
        'savedSubjectIDs', ...
        'savedChannelNames', ...
        'savedModelSignature', ...
        'savedSamplingRate', ...
        'savedNotchFrequencyHz', ...
        'savedNotchQualityFactor', ...
        'savedUseNormalizedProjection', ...
        '-v7.3');

end


%% ------------------------------------------------------------
% Validate scores
% ------------------------------------------------------------

if any(~isfinite(singleChannelScores(:)))

    error('NaN/Inf found in single-channel scores.');

end


if any(singleChannelScores(:) < 0)

    error('Negative LEAPD score found.');

end


% Geometric-mean classification is done in log-space.
% A true zero score is represented by realmin only for numerical logging;
% the predicted class is unchanged.
logScores = ...
    log(max(singleChannelScores, realmin('double')));


fprintf('Score matrix: %d channels x %d subjects\n', ...
    size(singleChannelScores,1), ...
    size(singleChannelScores,2));


%% ============================================================
% CREATE / LOAD EXACT 10,000 BALANCED REPEATS
%
% Each repeat:
%
%   13 TBI
%   13 Control
%
% All controls are fixed.
% 13 TBI are randomly sampled.
% ============================================================

fprintf('\n============================================================\n');
fprintf('BALANCED OOS SUBSETS\n');
fprintf('============================================================\n');


if isfile(subsetFile)

    fprintf('Loading existing enhanced subset file...\n');

    S = load(subsetFile);


    if ~isequal( ...
            string(S.savedSubjectIDs(:)), ...
            string(testSubjectIDs(:)))

        error('Balanced subset subject-order mismatch.');

    end


    selectedTBIRows = ...
        S.selectedTBIRows;


    fixedControlRows = ...
        S.fixedControlRows;


else

    rng(randomSeed);


    selectedTBIRows = ...
        zeros( ...
            numberOfRepeats, ...
            subjectsPerClass);


    for r = 1:numberOfRepeats

        localSelection = ...
            randperm( ...
                nTBI, ...
                subjectsPerClass);


        selectedTBIRows(r,:) = ...
            tbiRows(localSelection);

    end


    fixedControlRows = ...
        controlRows(:)';


    savedSubjectIDs = ...
        testSubjectIDs;


    save( ...
        subsetFile, ...
        'selectedTBIRows', ...
        'fixedControlRows', ...
        'savedSubjectIDs', ...
        'numberOfRepeats', ...
        'subjectsPerClass', ...
        'randomSeed', ...
        '-v7.3');

end


fprintf('Repeats: %d\n', size(selectedTBIRows,1));


%% ============================================================
% SUBJECT WEIGHTS
%
% Mean accuracy over all 10,000 balanced repeats can be written
% exactly as weighted subject-level correctness.
%
% Therefore we do NOT loop through 10,000 repeats during search.
% ============================================================

subjectUseCounts = ...
    zeros(numel(testClasses),1);


for r = 1:size(selectedTBIRows,1)

    subjectUseCounts(selectedTBIRows(r,:)) = ...
        subjectUseCounts(selectedTBIRows(r,:)) + 1;

end


subjectUseCounts(fixedControlRows) = ...
    size(selectedTBIRows,1);


totalDecisions = ...
    size(selectedTBIRows,1) * ...
    (subjectsPerClass + numel(fixedControlRows));


subjectWeights = ...
    subjectUseCounts / totalDecisions;


if abs(sum(subjectWeights) - 1) > 1e-12

    error('Subject weights do not sum to one.');

end


fprintf('Weighted search objective prepared.\n');


%% ============================================================
% SEARCH STORAGE
% ============================================================

topBySize = ...
    cell(10,1);


bestBySize = ...
    cell(10,1);


%% ============================================================
% EXACT SIZE 1
% ============================================================

fprintf('\n============================================================\n');
fprintf('EXACT SEARCH: 1 CHANNEL\n');
fprintf('============================================================\n');


combos = ...
    (1:nChannels)';


results = ...
    evaluate_binary_combinations( ...
        combos, ...
        logScores, ...
        testClasses, ...
        subjectWeights, ...
        channelNames, ...
        batchSize);


results = ...
    sortrows( ...
        results, ...
        'MeanAccuracy', ...
        'descend');


topBySize{1} = ...
    retain_beam_with_ties( ...
        results, ...
        beamWidth, ...
        maximumBeamRetained, ...
        tieTolerance);


bestBySize{1} = ...
    make_binary_best_row( ...
        1, ...
        results(1,:), ...
        "Exhaustive");


show_binary_winner(1,results(1,:));


%% ============================================================
% EXACT SIZE 2-4
% ============================================================

for combinationSize = 2:4

    fprintf('\n============================================================\n');
    fprintf('EXACT SEARCH: %d CHANNELS\n', combinationSize);
    fprintf('============================================================\n');


    combos = ...
        nchoosek( ...
            1:nChannels, ...
            combinationSize);


    fprintf('Combinations: %d\n', size(combos,1));


    results = ...
        evaluate_binary_combinations( ...
            combos, ...
            logScores, ...
            testClasses, ...
            subjectWeights, ...
            channelNames, ...
            batchSize);


    results = ...
        sortrows( ...
            results, ...
            'MeanAccuracy', ...
            'descend');


    topBySize{combinationSize} = ...
        retain_beam_with_ties( ...
            results, ...
            beamWidth, ...
            maximumBeamRetained, ...
            tieTolerance);


    bestBySize{combinationSize} = ...
        make_binary_best_row( ...
            combinationSize, ...
            results(1,:), ...
            "Exhaustive");


    show_binary_winner( ...
        combinationSize, ...
        results(1,:));

end


%% ============================================================
% EXACT SIZE 5 - MEMORY SAFE
% ============================================================

fprintf('\n============================================================\n');
fprintf('EXACT SEARCH: 5 CHANNELS - MEMORY SAFE\n');
fprintf('============================================================\n');


top5 = ...
    exhaustive_five_binary( ...
        logScores, ...
        testClasses, ...
        subjectWeights, ...
        channelNames, ...
        beamWidth, ...
        maximumBeamRetained, ...
        tieTolerance, ...
        batchSize);


topBySize{5} = ...
    top5;


bestBySize{5} = ...
    make_binary_best_row( ...
        5, ...
        top5(1,:), ...
        "Exhaustive");


show_binary_winner( ...
    5, ...
    top5(1,:));


%% ============================================================
% ENHANCED BEAM SEARCH 6-10
% ============================================================

for combinationSize = 6:10

    fprintf('\n============================================================\n');
    fprintf('ENHANCED BEAM SEARCH: %d CHANNELS\n', combinationSize);
    fprintf('============================================================\n');


    previousTop = ...
        topBySize{combinationSize-1};


    candidateCombos = ...
        expand_binary_beam( ...
            previousTop, ...
            nChannels);


    fprintf( ...
        'Unique candidates: %d\n', ...
        size(candidateCombos,1));


    results = ...
        evaluate_binary_combinations( ...
            candidateCombos, ...
            logScores, ...
            testClasses, ...
            subjectWeights, ...
            channelNames, ...
            batchSize);


    results = ...
        sortrows( ...
            results, ...
            'MeanAccuracy', ...
            'descend');


    topBySize{combinationSize} = ...
        retain_beam_with_ties( ...
            results, ...
            beamWidth, ...
            maximumBeamRetained, ...
            tieTolerance);


    fprintf( ...
        'Beam retained: %d\n', ...
        height(topBySize{combinationSize}));


    bestBySize{combinationSize} = ...
        make_binary_best_row( ...
            combinationSize, ...
            results(1,:), ...
            "EnhancedBeam");


    show_binary_winner( ...
        combinationSize, ...
        results(1,:));

end


%% ============================================================
% STAGE 1:
% ONE-SWAP LOCAL OPTIMIZATION
% TOP 100 TEN-CHANNEL BEAM SOLUTIONS
% ============================================================

fprintf('\n============================================================\n');
fprintf('STAGE 1: ONE-SWAP LOCAL SEARCH\n');
fprintf('============================================================\n');


nStart = ...
    min( ...
        localSwapTopN, ...
        height(topBySize{10}));


startSolutions = ...
    topBySize{10}(1:nStart,:);


oneSwapCells = ...
    cell(nStart,1);


if useParallel

    parfor i = 1:nStart

        oneSwapCells{i} = ...
            iterative_one_swap_binary( ...
                startSolutions.ChannelIndices{i}, ...
                logScores, ...
                testClasses, ...
                subjectWeights, ...
                channelNames, ...
                batchSize);

    end

else

    for i = 1:nStart

        oneSwapCells{i} = ...
            iterative_one_swap_binary( ...
                startSolutions.ChannelIndices{i}, ...
                logScores, ...
                testClasses, ...
                subjectWeights, ...
                channelNames, ...
                batchSize);

    end

end


oneSwapResults = ...
    vertcat(oneSwapCells{:});


oneSwapResults = ...
    unique_binary_solutions(oneSwapResults);


oneSwapResults = ...
    sortrows( ...
        oneSwapResults, ...
        'MeanAccuracy', ...
        'descend');


fprintf( ...
    'Unique one-swap local optima: %d\n', ...
    height(oneSwapResults));


fprintf( ...
    'Best after one-swap: %.6f%%\n', ...
    100*oneSwapResults.MeanAccuracy(1));


%% ============================================================
% STAGE 2:
% TWO-CHANNEL SWAP AROUND TOP LOCAL OPTIMA
%
% For a 10-channel set from 60:
%
% C(10,2) * C(50,2)
% = 55,125 neighbors per starting solution.
% ============================================================

fprintf('\n============================================================\n');
fprintf('STAGE 2: TWO-SWAP SEARCH\n');
fprintf('============================================================\n');


nTwoSwapStarts = ...
    min( ...
        twoSwapTopN, ...
        height(oneSwapResults));


twoSwapCells = ...
    cell(nTwoSwapStarts,1);


if useParallel

    parfor i = 1:nTwoSwapStarts

        twoSwapCells{i} = ...
            best_two_swap_binary( ...
                oneSwapResults.ChannelIndices{i}, ...
                logScores, ...
                testClasses, ...
                subjectWeights, ...
                channelNames, ...
                batchSize);

    end

else

    for i = 1:nTwoSwapStarts

        twoSwapCells{i} = ...
            best_two_swap_binary( ...
                oneSwapResults.ChannelIndices{i}, ...
                logScores, ...
                testClasses, ...
                subjectWeights, ...
                channelNames, ...
                batchSize);

    end

end


twoSwapResults = ...
    vertcat(twoSwapCells{:});


twoSwapResults = ...
    unique_binary_solutions(twoSwapResults);


twoSwapResults = ...
    sortrows( ...
        twoSwapResults, ...
        'MeanAccuracy', ...
        'descend');


fprintf( ...
    'Best after two-swap: %.6f%%\n', ...
    100*twoSwapResults.MeanAccuracy(1));


%% ============================================================
% STAGE 3:
% FINAL ONE-SWAP FROM EACH TWO-SWAP RESULT
% ============================================================

fprintf('\n============================================================\n');
fprintf('STAGE 3: FINAL ONE-SWAP\n');
fprintf('============================================================\n');


finalSwapCells = ...
    cell(height(twoSwapResults),1);


if useParallel

    parfor i = 1:height(twoSwapResults)

        finalSwapCells{i} = ...
            iterative_one_swap_binary( ...
                twoSwapResults.ChannelIndices{i}, ...
                logScores, ...
                testClasses, ...
                subjectWeights, ...
                channelNames, ...
                batchSize);

    end

else

    for i = 1:height(twoSwapResults)

        finalSwapCells{i} = ...
            iterative_one_swap_binary( ...
                twoSwapResults.ChannelIndices{i}, ...
                logScores, ...
                testClasses, ...
                subjectWeights, ...
                channelNames, ...
                batchSize);

    end

end


finalRefinementResults = ...
    vertcat(finalSwapCells{:});


finalRefinementResults = ...
    unique_binary_solutions( ...
        finalRefinementResults);


finalRefinementResults = ...
    sortrows( ...
        finalRefinementResults, ...
        'MeanAccuracy', ...
        'descend');


best10Refined = ...
    finalRefinementResults(1,:);


fprintf('\nBEST REFINED 10-CHANNEL COMBINATION\n');

fprintf('%s\n', ...
    best10Refined.Channels);

fprintf( ...
    'Weighted Mean Accuracy = %.6f%%\n', ...
    100*best10Refined.MeanAccuracy);


%% ============================================================
% REPLACE SIZE-10 WINNER IF REFINEMENT IMPROVED IT
% ============================================================

original10 = ...
    bestBySize{10};


if best10Refined.MeanAccuracy > ...
        original10.MeanAccuracy + tieTolerance

    fprintf( ...
        '\nRefinement improved 10-channel result:\n');

    fprintf( ...
        'Beam:    %.6f%%\n', ...
        100*original10.MeanAccuracy);

    fprintf( ...
        'Refined: %.6f%%\n', ...
        100*best10Refined.MeanAccuracy);


    bestBySize{10} = ...
        make_binary_best_row( ...
            10, ...
            best10Refined, ...
            "Beam+1Swap+2Swap+1Swap");

else

    fprintf( ...
        '\nRefinement did not improve the beam winner.\n');

end


%% ============================================================
% COMBINE BEST SEARCH RESULTS
% ============================================================

bestSearchBySize = ...
    vertcat(bestBySize{:});


%% ============================================================
% EXPLICIT 10,000-REPEAT METRICS FOR WINNERS
% ============================================================

fprintf('\n============================================================\n');
fprintf('EXPLICIT 10,000-REPEAT EVALUATION\n');
fprintf('============================================================\n');


finalRows = ...
    cell(10,1);


for combinationSize = 1:10

    combo = ...
        bestSearchBySize.ChannelIndices{combinationSize};


    repeatMetrics = ...
        evaluate_binary_repeats( ...
            combo, ...
            logScores, ...
            testClasses, ...
            selectedTBIRows, ...
            fixedControlRows);


    finalRows{combinationSize} = ...
        table( ...
            combinationSize, ...
            bestSearchBySize.Channels(combinationSize), ...
            bestSearchBySize.SearchMethod(combinationSize), ...
            100*repeatMetrics.MeanAccuracy, ...
            repeatMetrics.MeanErrorFraction, ...
            repeatMetrics.SDErrorFraction, ...
            100*repeatMetrics.MeanSensitivity, ...
            100*repeatMetrics.SDSensitivity, ...
            100*repeatMetrics.MeanSpecificity, ...
            100*repeatMetrics.SDSpecificity, ...
            100*repeatMetrics.MinimumAccuracy, ...
            100*repeatMetrics.MaximumAccuracy, ...
            'VariableNames', { ...
                'NumberOfChannels', ...
                'Channels', ...
                'SearchMethod', ...
                'MeanAccuracyPercent', ...
                'MeanErrorFraction', ...
                'SDErrorFraction', ...
                'MeanSensitivityPercent', ...
                'SDSensitivityPercent', ...
                'MeanSpecificityPercent', ...
                'SDSpecificityPercent', ...
                'MinimumAccuracyPercent', ...
                'MaximumAccuracyPercent'});

end


finalResults = ...
    vertcat(finalRows{:});


fprintf('\n============================================================\n');
fprintf('FINAL RESULTS\n');
fprintf('============================================================\n');


disp(finalResults);


%% ============================================================
% SAVE
% ============================================================

save( ...
    outputMAT, ...
    'analysisMode', ...
    'bestSearchBySize', ...
    'finalResults', ...
    'topBySize', ...
    'oneSwapResults', ...
    'twoSwapResults', ...
    'finalRefinementResults', ...
    'best10Refined', ...
    'singleChannelScores', ...
    'selectedTBIRows', ...
    'fixedControlRows', ...
    'subjectWeights', ...
    'channelNames', ...
    'trainingConfig', ...
    'samplingRate', ...
    'notchFrequencyHz', ...
    'notchQualityFactor', ...
    'useNormalizedProjection', ...
    '-v7.3');


if isfile(outputExcel)
    delete(outputExcel);
end


writetable( ...
    finalResults, ...
    outputExcel, ...
    'Sheet', ...
    'Best_By_Size');


writetable( ...
    bestSearchBySize, ...
    outputExcel, ...
    'Sheet', ...
    'Search_Winners');


writetable( ...
    oneSwapResults, ...
    outputExcel, ...
    'Sheet', ...
    'One_Swap_Results');


writetable( ...
    twoSwapResults, ...
    outputExcel, ...
    'Sheet', ...
    'Two_Swap_Results');


writetable( ...
    finalRefinementResults, ...
    outputExcel, ...
    'Sheet', ...
    'Final_Refinement');


for combinationSize = 1:10

    if isempty(topBySize{combinationSize})
        continue;
    end


    writetable( ...
        topBySize{combinationSize}, ...
        outputExcel, ...
        'Sheet', ...
        sprintf( ...
            'Top_%d_Channel', ...
            combinationSize));

end


fprintf('\nSaved:\n%s\n', outputMAT);
fprintf('%s\n', outputExcel);


%% ============================================================
% LOCAL FUNCTIONS
% ============================================================


function results = evaluate_binary_combinations( ...
    combos, ...
    logScores, ...
    trueClasses, ...
    subjectWeights, ...
    channelNames, ...
    batchSize)

    nCombos = ...
        size(combos,1);


    combinationSize = ...
        size(combos,2);


    meanAccuracy = ...
        nan(nCombos,1);


    threshold = ...
        combinationSize * log(0.5);


    for firstRow = 1:batchSize:nCombos

        lastRow = ...
            min( ...
                firstRow + batchSize - 1, ...
                nCombos);


        batchCombos = ...
            combos(firstRow:lastRow,:);


        nBatch = ...
            size(batchCombos,1);


        combinedLogScores = ...
            zeros( ...
                nBatch, ...
                size(logScores,2));


        for k = 1:combinationSize

            combinedLogScores = ...
                combinedLogScores + ...
                logScores( ...
                    batchCombos(:,k), ...
                    :);

        end


        predictions = ...
            combinedLogScores > threshold;


        class1Mask = ...
            trueClasses(:)' == 1;


        class0Mask = ...
            trueClasses(:)' == 0;


        correct = ...
            false(size(predictions));


        correct(:,class1Mask) = ...
            predictions(:,class1Mask);


        correct(:,class0Mask) = ...
            ~predictions(:,class0Mask);


        meanAccuracy(firstRow:lastRow) = ...
            double(correct) * ...
            subjectWeights(:);

    end


    channelCells = ...
        mat2cell( ...
            combos, ...
            ones(nCombos,1), ...
            combinationSize);


    channelStrings = ...
        strings(nCombos,1);


    for i = 1:nCombos

        channelStrings(i) = ...
            strjoin( ...
                channelNames(combos(i,:)), ...
                ', ');

    end


    results = ...
        table( ...
            channelCells, ...
            channelStrings, ...
            meanAccuracy, ...
            'VariableNames', { ...
                'ChannelIndices', ...
                'Channels', ...
                'MeanAccuracy'});

end


function retained = retain_beam_with_ties( ...
    results, ...
    beamWidth, ...
    maximumBeamRetained, ...
    tolerance)

    n = ...
        height(results);


    if n <= beamWidth

        retained = ...
            results;

        return;

    end


    cutoff = ...
        results.MeanAccuracy(beamWidth);


    keep = ...
        results.MeanAccuracy >= ...
        cutoff - tolerance;


    numberToKeep = ...
        sum(keep);


    if numberToKeep > maximumBeamRetained

        fprintf( ...
            ['Tie-aware beam wanted %d candidates; ' ...
             'capping at %d.\n'], ...
            numberToKeep, ...
            maximumBeamRetained);


        retained = ...
            results(1:maximumBeamRetained,:);

    else

        retained = ...
            results(keep,:);

    end

end


function topResults = exhaustive_five_binary( ...
    logScores, ...
    trueClasses, ...
    subjectWeights, ...
    channelNames, ...
    beamWidth, ...
    maximumBeamRetained, ...
    tieTolerance, ...
    batchSize)

    nChannels = ...
        size(logScores,1);


    total = ...
        nchoosek(nChannels,5);


    processed = ...
        0;


    topResults = ...
        table();


    timer = ...
        tic;


    fprintf( ...
        'Total combinations: %.0f\n', ...
        total);


    for firstChannel = 1:(nChannels-4)

        tails = ...
            nchoosek( ...
                (firstChannel+1):nChannels, ...
                4);


        combos = ...
            [ ...
                repmat( ...
                    firstChannel, ...
                    size(tails,1), ...
                    1), ...
                tails ...
            ];


        current = ...
            evaluate_binary_combinations( ...
                combos, ...
                logScores, ...
                trueClasses, ...
                subjectWeights, ...
                channelNames, ...
                batchSize);


        current = ...
            sortrows( ...
                current, ...
                'MeanAccuracy', ...
                'descend');


        current = ...
            retain_beam_with_ties( ...
                current, ...
                min(beamWidth,height(current)), ...
                maximumBeamRetained, ...
                tieTolerance);


        if isempty(topResults)

            topResults = ...
                current;

        else

            topResults = ...
                [topResults; current];


            topResults = ...
                sortrows( ...
                    topResults, ...
                    'MeanAccuracy', ...
                    'descend');


            topResults = ...
                retain_beam_with_ties( ...
                    topResults, ...
                    min(beamWidth,height(topResults)), ...
                    maximumBeamRetained, ...
                    tieTolerance);

        end


        processed = ...
            processed + ...
            size(combos,1);


        elapsed = ...
            toc(timer);


        fraction = ...
            processed / total;


        remaining = ...
            elapsed/fraction - elapsed;


        fprintf( ...
            ['First channel %2d/%2d | ' ...
             '%6.2f%% | elapsed %.1f min | remaining %.1f min\n'], ...
            firstChannel, ...
            nChannels-4, ...
            100*fraction, ...
            elapsed/60, ...
            remaining/60);

    end

end


function candidateCombos = expand_binary_beam( ...
    previousTop, ...
    nChannels)

    candidateCell = ...
        cell(0,1);


    counter = 0;


    for i = 1:height(previousTop)

        base = ...
            previousTop.ChannelIndices{i};


        available = ...
            setdiff( ...
                1:nChannels, ...
                base);


        for ch = available

            counter = ...
                counter + 1;


            candidateCell{counter,1} = ...
                sort([base ch]);

        end

    end


    candidateCombos = ...
        unique( ...
            vertcat(candidateCell{:}), ...
            'rows');

end


function result = iterative_one_swap_binary( ...
    startCombo, ...
    logScores, ...
    trueClasses, ...
    subjectWeights, ...
    channelNames, ...
    batchSize)

    currentCombo = ...
        sort(startCombo);


    current = ...
        evaluate_binary_combinations( ...
            currentCombo, ...
            logScores, ...
            trueClasses, ...
            subjectWeights, ...
            channelNames, ...
            batchSize);


    iterations = 0;


    while true

        nChannels = ...
            size(logScores,1);


        outside = ...
            setdiff( ...
                1:nChannels, ...
                currentCombo);


        candidates = ...
            zeros( ...
                numel(currentCombo)*numel(outside), ...
                numel(currentCombo));


        row = 0;


        for removePosition = 1:numel(currentCombo)

            for addChannel = outside

                row = row + 1;


                candidate = ...
                    currentCombo;


                candidate(removePosition) = ...
                    addChannel;


                candidates(row,:) = ...
                    sort(candidate);

            end

        end


        candidates = ...
            unique( ...
                candidates, ...
                'rows');


        evaluated = ...
            evaluate_binary_combinations( ...
                candidates, ...
                logScores, ...
                trueClasses, ...
                subjectWeights, ...
                channelNames, ...
                batchSize);


        evaluated = ...
            sortrows( ...
                evaluated, ...
                'MeanAccuracy', ...
                'descend');


        if evaluated.MeanAccuracy(1) > ...
                current.MeanAccuracy(1) + 1e-12

            current = ...
                evaluated(1,:);


            currentCombo = ...
                current.ChannelIndices{1};


            iterations = ...
                iterations + 1;

        else

            break;

        end

    end


    result = ...
        current;


    result.OneSwapIterations = ...
        iterations;

end


function result = best_two_swap_binary( ...
    startCombo, ...
    logScores, ...
    trueClasses, ...
    subjectWeights, ...
    channelNames, ...
    batchSize)

    startCombo = ...
        sort(startCombo);


    current = ...
        evaluate_binary_combinations( ...
            startCombo, ...
            logScores, ...
            trueClasses, ...
            subjectWeights, ...
            channelNames, ...
            batchSize);


    nChannels = ...
        size(logScores,1);


    outside = ...
        setdiff( ...
            1:nChannels, ...
            startCombo);


    removePairs = ...
        nchoosek( ...
            1:numel(startCombo), ...
            2);


    addPairs = ...
        nchoosek( ...
            outside, ...
            2);


    nCandidates = ...
        size(removePairs,1) * ...
        size(addPairs,1);


    candidates = ...
        zeros( ...
            nCandidates, ...
            numel(startCombo));


    row = 0;


    for r = 1:size(removePairs,1)

        for a = 1:size(addPairs,1)

            row = row + 1;


            candidate = ...
                startCombo;


            candidate(removePairs(r,:)) = ...
                addPairs(a,:);


            candidates(row,:) = ...
                sort(candidate);

        end

    end


    candidates = ...
        unique( ...
            candidates, ...
            'rows');


    evaluated = ...
        evaluate_binary_combinations( ...
            candidates, ...
            logScores, ...
            trueClasses, ...
            subjectWeights, ...
            channelNames, ...
            batchSize);


    evaluated = ...
        sortrows( ...
            evaluated, ...
            'MeanAccuracy', ...
            'descend');


    if evaluated.MeanAccuracy(1) > ...
            current.MeanAccuracy(1) + 1e-12

        result = ...
            evaluated(1,:);


        result.TwoSwapImproved = ...
            true;

    else

        result = ...
            current;


        result.TwoSwapImproved = ...
            false;

    end

end


function results = unique_binary_solutions(results)

    keys = ...
        strings(height(results),1);


    for i = 1:height(results)

        combo = ...
            sort(results.ChannelIndices{i});


        keys(i) = ...
            strjoin( ...
                string(combo), ...
                '_');

    end


    [~, uniqueIndices] = ...
        unique( ...
            keys, ...
            'stable');


    results = ...
        results(uniqueIndices,:);

end


function metrics = evaluate_binary_repeats( ...
    combo, ...
    logScores, ...
    trueClasses, ...
    selectedTBIRows, ...
    controlRows)

    combinedLogScore = ...
        sum( ...
            logScores(combo,:), ...
            1);


    threshold = ...
        numel(combo) * log(0.5);


    predictions = ...
        double( ...
            combinedLogScore > threshold);


    nRepeats = ...
        size(selectedTBIRows,1);


    accuracy = ...
        nan(nRepeats,1);


    sensitivity = ...
        nan(nRepeats,1);


    specificity = ...
        nan(nRepeats,1);


    for r = 1:nRepeats

        rows = ...
            [ ...
                selectedTBIRows(r,:), ...
                controlRows ...
            ];


        truth = ...
            trueClasses(rows);


        pred = ...
            predictions(rows)';


        TP = ...
            sum( ...
                truth == 1 & ...
                pred == 1);


        TN = ...
            sum( ...
                truth == 0 & ...
                pred == 0);


        FP = ...
            sum( ...
                truth == 0 & ...
                pred == 1);


        FN = ...
            sum( ...
                truth == 1 & ...
                pred == 0);


        accuracy(r) = ...
            (TP+TN)/numel(rows);


        sensitivity(r) = ...
            TP/(TP+FN);


        specificity(r) = ...
            TN/(TN+FP);

    end


    %% Error fraction for each balanced repeat.
    % Example: 20%% error is stored as 0.20, not 20.
    errorFraction = ...
        1 - accuracy;


    metrics.MeanAccuracy = ...
        mean(accuracy);


    metrics.MeanErrorFraction = ...
        mean(errorFraction);


    metrics.SDErrorFraction = ...
        std(errorFraction);


    metrics.MeanSensitivity = ...
        mean(sensitivity);


    metrics.SDSensitivity = ...
        std(sensitivity);


    metrics.MeanSpecificity = ...
        mean(specificity);


    metrics.SDSpecificity = ...
        std(specificity);


    metrics.MinimumAccuracy = ...
        min(accuracy);


    metrics.MaximumAccuracy = ...
        max(accuracy);

end


function row = make_binary_best_row( ...
    numberOfChannels, ...
    source, ...
    method)

    row = ...
        table( ...
            numberOfChannels, ...
            source.ChannelIndices, ...
            source.Channels, ...
            string(method), ...
            source.MeanAccuracy, ...
            'VariableNames', { ...
                'NumberOfChannels', ...
                'ChannelIndices', ...
                'Channels', ...
                'SearchMethod', ...
                'MeanAccuracy'});

end


function show_binary_winner( ...
    combinationSize, ...
    result)

    fprintf('\nBest %d-channel:\n', combinationSize);

    fprintf('%s\n', result.Channels);

    fprintf( ...
        'Mean balanced accuracy = %.6f%%\n', ...
        100*result.MeanAccuracy);

end