clear; clc;

%% USER SETTINGS
projectRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(projectRoot, 'functions'));

resultsFolder = fullfile(projectRoot, 'results');
if ~isfolder(resultsFolder), mkdir(resultsFolder); end

% Choose: 'binary' or 'correlation'
config.analysisType = 'binary';

config.developmentFile = fullfile( ...
    projectRoot, 'data', 'development_dataset.mat');

config.testFile = fullfile( ...
    projectRoot, 'data', 'independent_test_dataset.mat');

% Leave empty to auto-resolve when exactly one matching step-1 file exists.
% Otherwise provide the exact MAT-file path.
config.hyperparameterFile = '';

config.samplingRate = 500;
config.notchFrequencyHz = 60;
config.notchQualityFactor = 35;
config.useNormalizedProjection = false;

config.excludedChannels = {};

% Channel combinations are searched on the TEST dataset.
% They are not fixed from development.
config.minimumCombinationSize = 1;
config.maximumCombinationSize = 5;

config.topKPerSize = 1000;
config.combinationBatchSize = 10000;

config.useParallel = true;
config.numberOfWorkers = [];

%% ANALYSIS-SPECIFIC SETTINGS
switch lower(config.analysisType)

    case 'binary'
        config.outputFile = fullfile( ...
            resultsFolder, 'out_of_sample_evaluation_binary.mat');

        config.excelFile = fullfile( ...
            resultsFolder, 'out_of_sample_results_binary.xlsx');

    case 'correlation'
        config.testTargetFile = fullfile( ...
            projectRoot, 'data', 'test_targets.xlsx');

        config.subjectIDColumn = 'ID';
        config.targetColumn = 'Target';

        % 'min', 'max', or 'maxabs'
        config.selectionCriterion = 'max';

        targetLabel = matlab.lang.makeValidName(config.targetColumn);

        config.outputFile = fullfile( ...
            resultsFolder, ...
            sprintf('out_of_sample_evaluation_correlation_%s.mat', ...
                targetLabel));

        config.excelFile = fullfile( ...
            resultsFolder, ...
            sprintf('out_of_sample_results_correlation_%s.xlsx', ...
                targetLabel));

    otherwise
        error('Unknown analysisType: "%s".', config.analysisType);
end

%% START PARALLEL POOL
if config.useParallel
    pool = gcp('nocreate');

    if isempty(pool)
        if isempty(config.numberOfWorkers)
            pool = parpool;
        else
            pool = parpool(config.numberOfWorkers);
        end
    end

    fprintf('\nParallel pool active with %d workers.\n', ...
        pool.NumWorkers);
end

%% LOAD FIXED CHANNEL-SPECIFIC HYPERPARAMETERS
config.hyperparameterFile = resolve_hyperparameter_file( ...
    resultsFolder, config.analysisType, config.hyperparameterFile);

fprintf('Using hyperparameter file:\n%s\n', ...
    config.hyperparameterFile);

candidateModels = load_candidate_models( ...
    config.hyperparameterFile, config.excludedChannels);

disp(candidateModels(:, { ...
    'Channel','LowCutoffHz','HighCutoffHz', ...
    'LPCOrder','PCADimension'}));

%% LOAD DEVELOPMENT AND TEST DATA
developmentData = load_leapd_dataset(config.developmentFile);
testData = load_leapd_dataset(config.testFile);

validate_selected_channels( ...
    developmentData, ...
    testData, ...
    cellstr(string(candidateModels.Channel)));

switch lower(config.analysisType)

    case 'binary'
        fprintf('\nFitting final binary channel models...\n');

        finalModels = fit_binary_channel_models( ...
            developmentData, candidateModels, config);

        fprintf('\nScoring independent binary test subjects...\n');

        [channelIndices, classes, subjectIDs] = ...
            score_binary_channel_models( ...
                testData, finalModels, config);

        [combinationResults, bestBySize, bestScoreTable] = ...
            evaluate_binary_combinations( ...
                channelIndices, ...
                classes, ...
                subjectIDs, ...
                string(candidateModels.Channel), ...
                config.minimumCombinationSize, ...
                config.maximumCombinationSize, ...
                config.topKPerSize, ...
                config.combinationBatchSize, ...
                config.useParallel);

        save(config.outputFile, ...
            'combinationResults', ...
            'bestBySize', ...
            'bestScoreTable', ...
            'candidateModels', ...
            'channelIndices', ...
            'classes', ...
            'subjectIDs', ...
            'finalModels', ...
            'config', ...
            '-v7.3');

        writetable(combinationResults, ...
            config.excelFile, 'Sheet', 'Top_Combinations');

        writetable(bestBySize, ...
            config.excelFile, 'Sheet', 'Best_By_Size');

        writetable(bestScoreTable, ...
            config.excelFile, 'Sheet', 'Best_Subject_Indices');

        fprintf('\n');
        fprintf('============================================================\n');
        fprintf('                BEST TEST-SET RESULTS\n');
        fprintf('============================================================\n\n');

        disp(bestBySize(:, { ...
            'NumberOfChannels','Channels','Accuracy', ...
            'BalancedAccuracy','Sensitivity','Specificity'}));

    case 'correlation'
        fprintf('\nFitting final correlation channel models...\n');

        finalModels = fit_correlation_channel_models( ...
            developmentData, candidateModels, config);

        fprintf('\nScoring independent correlation test subjects...\n');

        [channelIndices, subjectIDs] = ...
            score_correlation_channel_models( ...
                testData, finalModels, config);

        targetData = load_correlation_targets( ...
            config.testTargetFile, ...
            config.subjectIDColumn, ...
            config.targetColumn);

        % Test datasets may contain subjects without a target value.
        targetValues = match_correlation_targets( ...
            subjectIDs, targetData, false);

        [combinationResults, bestBySize, bestScoreTable] = ...
            evaluate_correlation_combinations( ...
                channelIndices, ...
                targetValues, ...
                subjectIDs, ...
                string(candidateModels.Channel), ...
                config.minimumCombinationSize, ...
                config.maximumCombinationSize, ...
                config.selectionCriterion, ...
                config.topKPerSize, ...
                config.combinationBatchSize, ...
                config.useParallel);

        save(config.outputFile, ...
            'combinationResults', ...
            'bestBySize', ...
            'bestScoreTable', ...
            'candidateModels', ...
            'channelIndices', ...
            'subjectIDs', ...
            'targetValues', ...
            'finalModels', ...
            'config', ...
            '-v7.3');

        writetable(combinationResults, ...
            config.excelFile, 'Sheet', 'Top_Combinations');

        writetable(bestBySize, ...
            config.excelFile, 'Sheet', 'Best_By_Size');

        writetable(bestScoreTable, ...
            config.excelFile, 'Sheet', 'Best_Combined_Indices');

        fprintf('\n');
        fprintf('============================================================\n');
        fprintf('             BEST TEST-SET CORRELATIONS\n');
        fprintf('============================================================\n\n');

        disp(bestBySize(:, { ...
            'NumberOfChannels','Channels', ...
            'SpearmanRho','PValue','NValid'}));
end

fprintf(['\nNote: channel-specific hyperparameters are fixed from ', ...
    'development, but channel combinations are ranked on the test set.\n']);

fprintf('\nSaved MAT results to:\n%s\n', config.outputFile);
fprintf('\nSaved Excel results to:\n%s\n', config.excelFile);
